# Generated by Django 2.2.1 on 2019-05-30 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_codigo'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistance',
            name='question_text',
        ),
        migrations.CreateModel(
            name='BeaconEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
    ]
