# Generated by Django 2.2.2 on 2019-06-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190630_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
