# Generated by Django 2.2.2 on 2019-06-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personevent',
            name='state',
            field=models.IntegerField(default=False),
        ),
    ]
