# Generated by Django 2.2.2 on 2019-06-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20190630_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personevent',
            old_name='state',
            new_name='status',
        ),
    ]
