# Generated by Django 2.2.2 on 2019-07-01 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20190630_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beaconevent',
            name='beacon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beacon.Beacon'),
        ),
    ]
