# Generated by Django 2.2.3 on 2019-07-10 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20190701_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 16, 21, 57, 439211)),
        ),
    ]
