# Generated by Django 2.2.1 on 2019-05-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='codigo',
            field=models.CharField(default='', max_length=8),
        ),
    ]
